import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Download, ArrowLeft, Loader2 } from "lucide-react";
import { motion } from "framer-motion";
import { useToast } from "@/hooks/use-toast";

interface ManualPage {
  pageNumber: number;
  title: string;
  instructions: string;
  partsNeeded: string[];
  tip?: string;
  imageUrl?: string;
}

interface Manual {
  id: string;
  title: string;
  description: string;
  page_count: number;
  status: string;
  content: { pages: ManualPage[] } | null;
  created_at: string;
}

const ManualView = () => {
  const { id } = useParams();
  const [manual, setManual] = useState<Manual | null>(null);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  useEffect(() => {
    const fetchManual = async () => {
      if (!id) return;
      const { data, error } = await supabase
        .from("manuals")
        .select("*")
        .eq("id", id)
        .maybeSingle();

      if (error) {
        console.error("Error fetching manual:", error);
      }
      setManual(data as unknown as Manual | null);
      setLoading(false);
    };

    fetchManual();
  }, [id]);

  const handleDownloadPDF = () => {
    if (!manual?.content?.pages) return;

    // Generate a simple HTML-based printable document
    const pages = manual.content.pages;
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${manual.title} - BrickBooks Manual</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Fredoka:wght@400;600;700&family=Inter:wght@400;500&display=swap');
          body { font-family: 'Inter', sans-serif; margin: 0; padding: 20px; color: #1a1a2e; }
          h1 { font-family: 'Fredoka', sans-serif; color: #d32f2f; text-align: center; font-size: 2em; margin-bottom: 0.5em; }
          .subtitle { text-align: center; color: #666; margin-bottom: 2em; }
          .page { page-break-after: always; padding: 20px; margin-bottom: 20px; border: 2px solid #eee; border-radius: 12px; }
          .page:last-child { page-break-after: auto; }
          .page-header { display: flex; align-items: center; gap: 12px; margin-bottom: 16px; }
          .step-number { background: #d32f2f; color: white; width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-family: 'Fredoka', sans-serif; font-weight: 700; font-size: 1.2em; }
          .page-title { font-family: 'Fredoka', sans-serif; font-size: 1.4em; font-weight: 600; }
          .instructions { line-height: 1.8; margin: 16px 0; font-size: 1em; }
          .parts { background: #f5f5f5; padding: 12px 16px; border-radius: 8px; margin: 12px 0; }
          .parts h4 { font-family: 'Fredoka', sans-serif; margin: 0 0 8px 0; color: #333; }
          .parts ul { margin: 0; padding-left: 20px; }
          .parts li { margin: 4px 0; }
          .tip { background: #fff8e1; border-left: 4px solid #ffc107; padding: 12px 16px; border-radius: 0 8px 8px 0; margin-top: 12px; font-style: italic; }
          .footer { text-align: center; color: #999; font-size: 0.8em; margin-top: 2em; }
          @media print { .page { border: none; } }
        </style>
      </head>
      <body>
        <h1>🧱 ${manual.title}</h1>
        <p class="subtitle">${manual.description}</p>
        ${pages.map(page => `
          <div class="page">
            <div class="page-header">
              <div class="step-number">${page.pageNumber}</div>
              <div class="page-title">${page.title}</div>
            </div>
            ${page.imageUrl ? `<div style="margin-bottom: 16px; border-radius: 8px; overflow: hidden;"><img src="${page.imageUrl}" alt="Step ${page.pageNumber}" style="width: 100%; height: auto;" /></div>` : ''}
            <div class="instructions">${page.instructions}</div>
            <div class="parts">
              <h4>🔧 Parts Needed:</h4>
              <ul>
                ${page.partsNeeded.map(part => `<li>${part}</li>`).join('')}
              </ul>
            </div>
            ${page.tip ? `<div class="tip">💡 Tip: ${page.tip}</div>` : ''}
          </div>
        `).join('')}
        <div class="footer">Generated by BrickBooks — AI-Powered LEGO Manual Creator</div>
      </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      setTimeout(() => printWindow.print(), 500);
    }

    toast({ title: "PDF Ready", description: "Use your browser's Print dialog to save as PDF." });
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex flex-col">
        <Navbar />
        <main className="flex-1 flex items-center justify-center">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
        </main>
        <Footer />
      </div>
    );
  }

  if (!manual) {
    return (
      <div className="min-h-screen bg-background flex flex-col">
        <Navbar />
        <main className="flex-1 flex items-center justify-center flex-col gap-4">
          <h1 className="text-2xl font-heading font-bold text-foreground">Manual Not Found</h1>
          <Link to="/gallery">
            <Button variant="outline">Back to Gallery</Button>
          </Link>
        </main>
        <Footer />
      </div>
    );
  }

  const pages = manual.content?.pages || [];

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      <main className="flex-1 py-12">
        <div className="container mx-auto px-4 max-w-3xl">
          <div className="flex items-center justify-between mb-8">
            <Link to="/gallery">
              <Button variant="ghost" className="gap-2">
                <ArrowLeft className="w-4 h-4" />
                Back
              </Button>
            </Link>
            {manual.status === "completed" && pages.length > 0 && (
              <Button onClick={handleDownloadPDF} className="gap-2">
                <Download className="w-4 h-4" />
                Download PDF
              </Button>
            )}
          </div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <h1 className="text-3xl md:text-4xl font-heading font-bold text-foreground mb-2">
              {manual.title}
            </h1>
            <p className="text-muted-foreground mb-8">{manual.description}</p>

            {manual.status === "generating" && (
              <div className="bg-card rounded-2xl p-12 shadow-card text-center">
                <Loader2 className="w-12 h-12 animate-spin text-primary mx-auto mb-4" />
                <p className="font-heading font-semibold text-foreground">Generating your manual...</p>
                <p className="text-muted-foreground text-sm mt-1">This may take a minute.</p>
              </div>
            )}

            {manual.status === "failed" && (
              <div className="bg-destructive/10 rounded-2xl p-8 text-center">
                <p className="font-heading font-semibold text-destructive">Generation failed</p>
                <p className="text-muted-foreground text-sm mt-1">Please try creating a new manual.</p>
              </div>
            )}

            {manual.status === "completed" && pages.length > 0 && (
              <div className="space-y-6">
                {pages.map((page) => (
                  <motion.div
                    key={page.pageNumber}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: page.pageNumber * 0.05 }}
                    className="bg-card rounded-2xl p-6 shadow-card"
                  >
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-10 h-10 rounded-full bg-primary flex items-center justify-center">
                        <span className="text-primary-foreground font-heading font-bold">
                          {page.pageNumber}
                        </span>
                      </div>
                      <h2 className="font-heading font-bold text-xl text-foreground">{page.title}</h2>
                    </div>

                    {page.imageUrl && (
                      <div className="mb-4 rounded-xl overflow-hidden border border-border">
                        <img
                          src={page.imageUrl}
                          alt={`Step ${page.pageNumber}: ${page.title}`}
                          className="w-full h-auto"
                          loading="lazy"
                        />
                      </div>
                    )}

                    <p className="text-foreground leading-relaxed mb-4">{page.instructions}</p>

                    <div className="bg-muted rounded-xl p-4 mb-3">
                      <h4 className="font-heading font-semibold text-sm text-foreground mb-2">🔧 Parts Needed:</h4>
                      <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1">
                        {page.partsNeeded.map((part, idx) => (
                          <li key={idx}>{part}</li>
                        ))}
                      </ul>
                    </div>

                    {page.tip && (
                      <div className="bg-secondary/20 border-l-4 border-secondary rounded-r-xl p-3">
                        <p className="text-sm text-foreground">💡 <strong>Tip:</strong> {page.tip}</p>
                      </div>
                    )}
                  </motion.div>
                ))}
              </div>
            )}
          </motion.div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default ManualView;
